{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "camunda-cawemo.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "camunda-cawemo.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  type: {{ .Values.service.type }}*/}}
{{/*  ports:*/}}
{{/*    - port: {{ .Values.service.port }}*/}}
{{/*      targetPort: http*/}}
{{/*      protocol: TCP*/}}
{{/*      name: http*/}}
{{/*  selector:*/}}
{{/*    {{- include "camunda-cawemo.selectorLabels" . | nindent 4 }}*/}}
